pub static ANY: &str = "any";
pub static STRING: &str = "string";
pub static INT: &str = "int64";
pub static FLOAT: &str = "float64";
pub static BOOL: &str = "bool";
pub static PTR: &str = "*";
pub static NOT_NULL: &str = "";
pub static AUTO_GENERATED: &str = "AutoGenerated";
