// RUST_TYPES
// considering serde_json is being used:
pub static RUST_ANY: &str = "Option<Value>";
pub static RUST_STRING: &str = "String";
pub static RUST_INT: &str = "isize";
pub static RUST_FLOAT: &str = "f64";
pub static RUST_BOOL: &str = "bool";
pub static RUST_AUTO_GENERATED: &str = "AutoGenerated";

// SCALA_TYPES
pub static SCALA_ANY: &str = "Any";
pub static SCALA_STRING: &str = "String";
pub static SCALA_INT: &str = "Int";
pub static SCALA_FLOAT: &str = "Float";
pub static SCALA_BOOL: &str = "Boolean";
pub static SCALA_AUTO_GENERATED: &str = "AutoGenerated";

// GO_TYPES
pub static GO_ANY: &str = "any";
pub static GO_STRING: &str = "string";
pub static GO_INT: &str = "int64";
pub static GO_FLOAT: &str = "float64";
pub static GO_BOOL: &str = "bool";
pub static GO_PTR: &str = "*";
pub static GO_NOT_NULL: &str = "";
pub static GO_AUTO_GENERATED: &str = "AutoGenerated";

// JAVA_TYPES
pub static JAVA_ANY: &str = "Object";
pub static JAVA_STRING: &str = "String";
pub static JAVA_INT: &str = "Integer";
pub static JAVA_FLOAT: &str = "Float";
pub static JAVA_BOOL: &str = "boolean";
pub static JAVA_AUTO_GENERATED: &str = "AutoGenerated";

pub static DEFAULT_LANG: &str = "rust";
